### ISSUE TITLE
backend: signup / sign in

### ISSUE THREAD

**Issue by daberry** [hrr24-melmac/Findabuddy#21]

**Comment by aajungroth** [comment]
- I'm switching the back end from using cookie parser and express-session to express-session and connect-mongodb-session. 
- Express-session no longer needs cookie parser and can make its own secrets. 
- Express-session has a memory store which is only good for development and testing. 
- It gave a list of compatible alternatives. 
   -- I went with connect-mongodb-session because it's built for and maintained by mongodb.

**Comment by daberry** [comment]
whatever makes storing sessions in mongo easier to implement!

**Comment by aajungroth** [comment]
Wrote post login route handler, I need to add tests cases and possibly refactor pieces into helper functions

**Comment by aajungroth** [comment]
Making a pull request that has log in and log out. The functions may need some work. I'm going to do sign up next.
